### ISSUE TITLE
Moments after `getAccount()` is called, debug console is flooded with errors

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#156]
## Current Behavior
Debug Console is flooded with errors until ram runs out when initializing a wallet and calling `getAccount()`
```
SimplifiedMNList.js:298 Uncaught (in promise) Error: Unknown network
    at SimplifiedMNList.getLLMQTypes (SimplifiedMNList.js:298)
    at SimplifiedMNList.addOrUpdateQuorums [as addAndMaybeRemoveQuorums] (SimplifiedMNList.js:126)
```

```
Uncaught (in promise) Error: Unknown network
    at SimplifiedMNList.getLLMQTypes (SimplifiedMNList.js:298)
```

## Your Environment
* Version used:
```
└─┬ dash@3.13.3
  └── @dashevo/wallet-lib@7.13.3 
```
* Chrome, Nuxt, webpack

**Comment by Alex-Werner** [comment]
cc: @antouhou @Cofresi @shumkov

**Comment by Alex-Werner** [comment]
From Wallet-lib, this is triggered when we call our transporter methods (subscribeToBlocks, fetchAddressTransactions, subscribeToTransactions, getUTXO, ...) basically everything related to our transporter. 
And is due to `this.network` being undefined in usage

**Comment by Alex-Werner** [comment]
Work in progress here : https://github.com/dashevo/dapi-client/pull/161

**Comment by shumkov** [comment]
@dashameter should be fixed in https://github.com/dashevo/DashJS/releases/tag/v3.13.4

**Comment by eltNEG** [comment]
@shumkov 

For wallet version `"@dashevo/wallet-lib": "7.13.4"`, I am getting the error below when I tried to use this package in a project. It works fine in offline mode. 

```
config
const opts = {
    network: 'livenet',
    // offlineMode: true,
    HDPublicKey:"",
};

const wallet = new Wallet(opts);
```

Error when `wallet.getAccount()` is called

```
(node:3140) UnhandledPromiseRejectionWarning: Error: Failed to perform standard injections with reason: Plugin ChainPlugin of type Standard onStart failed. Reason: Cannot destructure property 'blockHeight' of 'store.chains[network]' as it is undefined.
```

When the network is changed to `testnet`, it throws the error below:

```
(node:3189) UnhandledPromiseRejectionWarning: Error: Failed to perform standard injections with reason: Worker IdentitySyncWorker failed onStart. Reason: Worker IdentitySyncWorker failed onExecute. Reason: 13 INTERNAL: Internal error
```

`Is it reliable to use the provided 'public nodes' in production?`

**Comment by shumkov** [comment]
We refactored DAPI Client and Wallet transport logic in 0.14 version (7.14 for wallet) which will be released in a few days. I hope your issues will disappear. Otherwise, we will dive into them.

**Comment by eltNEG** [comment]
> We refactored DAPI Client and Wallet transport logic in 0.14 version (7.14 for wallet) which will be released in a few days. I hope your issues will disappear. Otherwise, we will dive into them.

Thanks, @shumkov. I will wait for the new version. In case you missed it, is it safe to use the public nodes provided by the module in production? My plan is to introduce this module to some crypto apps so that they can easily add dash to it. For example, coinprofile.co can easily add dash if this is reliable enough to be used in production.

**Comment by shumkov** [comment]
@eltNEG We are not on the production stage yet. Wallet lib and other Dash Platform components by default work with Evonet - testnet for Dash Evolution release. I strongly do not recommend to use Evonet for production purposes.

**Comment by eltNEG** [comment]
Thanks @shumkov

**Comment by dashameter** [comment]
closing for now as it appears fixed
